# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: wwx2604
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: breaking-news
service: serverless-MoranSin

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'
      
plugins:
  - serverless-python-requirements