service: lambda-crud

provider:
  name: aws
  runtime: python3.11

functions:
  health:
    handler: handler.health_check
    events:
      - http:
          path: health
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
