version: '3.9'

services:
  scraper:
    build: ./lambda-scraper
    ports:
      - "8000:8000"

  processor:
    build: ./lambda-processor

  crud:
    build: ./lambda-crud
    ports:
      - "8001:8001"

  sqs:
    image: softwaremill/elasticmq:latest
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
  