service: data-pipeline

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

functions:
  scraper:
    handler: lambda-scraper/handler.handler
    events:
      - http:
          path: scrape
          method: post

  processor:
    handler: lambda-processor/handler.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - DataRawQueue
              - Arn

  crud:
    handler: lambda-crud/handler.handler
    events:
      - http:
          path: health
          method: get
      - http:
          path: users
          method: post

resources:
  Resources:
    DataRawQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: data-raw-q
