version: '3.7'

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION_NAME=${REGION_NAME}
      - QUEUE_URL=${QUEUE_URL}
    volumes:
      - .:/usr/src/app

  sqs:
    image: softwaremill/elasticmq
    ports:
      - "9324:9324"
