service: breaking-news-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

package:
  exclude:
    - node_modules/**
    - __pycache__/**
    - .serverless/**
    - .venv/**

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements
  - serverless-offline # for local development

custom:
  serverless-offline:
    port: 3000  # Set the port to 3000
    host: 0.0.0.0  # Ensure it's listening on all interfaces