service: lambda-crud

provider:
  name: aws
  runtime: python3.11

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3001
