service: ynet-breaking-news-api

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  app:
    handler: handler.main
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

package:
  exclude:
    - node_modules/**
    - venv/**
    - __pycache__/**
