version: '3.8'

services:
  sqs:
    image: softwaremill/elasticmq:latest
    container_name: sqs
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
  sqs-create:
    image: amazon/aws-cli:latest
    container_name: sqs-create
    links:
      - sqs
    entrypoint: sh
    volumes:
      - ./:/project
      - ./create-queues.sh:/project/create-queues.sh:ro
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ENDPOINT_URL=http://sqs:9324
    command: " ./create-queues.sh"
  backend:
    build:
      context: .
    privileged: true
    working_dir: /app
    ports:
      - '8000:8000'
    container_name: backend-api
    volumes:
      - .:/app
    depends_on:
      - sqs
      - sqs-create
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ENDPOINT_URL=http://sqs:9324
