service: lambda-scraper

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  scraper:
    handler: handler.scrape
    events:
      - http:
          path: scrape
          method: post
