services:
  sqs:
    image: softwaremill/elasticmq:latest
    ports:
      - "9324:9324"
  
  sls:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    container_name: sls
    image: sls:latest
    depends_on:
      - sqs
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ENDPOINT_URL=http://sqs:9324

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    volumes:
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
