service: breaking-news-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  timeout: 30

package:
  exclude:
    - node_modules/**
    - __pycache__/**
    - .serverless/**
    - .venv/**

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements
  - serverless-offline # for local development

custom:
    servless-offline:
    host:0.0.0.0
    port: 3000