service: ynet-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  app:
    handler: main.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements
