version: '3.8'

services:
  scraper:
    build: ./lambda-scraper
    ports:
      - "8000:8000"
    depends_on:
      - sqs
  
  processor:
    build: ./lambda-processor
    ports:
      - "3001:3000"
    depends_on:
      - sqs
  
  crud:
    build: ./lambda-crud
    ports:
      - "3002:3000"

  sqs:
    image: softwaremill/elasticmq:latest
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
