service: lambda-processor
frameworkVersion: ">3.0.0 || <4.0.0"
provider:
  name: aws
  runtime: python3.9

functions:
  process:
    handler: handler.process_message
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - DataRawQueue
              - Arn

resources:
  Resources:
    DataRawQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: data-raw-q

plugins:
  - serverless-python-requirements
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3196
  serverless-offline-sqs:
    endpoint: http://sqs:9324
    accessKetId: x
    secretAccessKey: x
  pythonRequirements:
    dockerizePip: true
