service: lambda-crud
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11

package:
  exclude:
    - node_modules/**
    - __pycache__/**
    - .serverless/**
    - .venv/**

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000

plugins:
  - serverless-offline
  - serverless-python-requirements
