services:
  sqs:
    image: softwaremill/elasticmq:latest
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

  lambda-scraper:
    build: ./lambda-scraper
    command: uvicorn handler:app --host 0.0.0.0 --port 7000
    ports:
      - "7000:7000"
    environment:
      - SQS_ENDPOINT_URL=http://sqs:9324
    depends_on:
      - sqs
      - db

  lambda-processor:
    build: ./lambda-processor
    command: uvicorn handler:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - SQS_ENDPOINT_URL=http://sqs:9324
    depends_on:
      - sqs
      - db   

  lambda-crud:
    build: ./lambda-crud
    command: uvicorn handler:app --host 0.0.0.0 --port 9000
    ports:
      - "9000:9000"
    environment:
      - SQS_ENDPOINT_URL=http://sqs:9324
    depends_on:
      - sqs
      - db      
       

  db:
    image: postgres:13
    container_name: postgres-database
    environment:
      POSTGRES_USER: myPOSTGRES    
      POSTGRES_PASSWORD: myPOSTGRES  
      POSTGRES_DB: mydatabase     
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
