service: lambda-scraper

provider:
  name: aws
  runtime: python3.11

functions:
  app:
    handler: handler.app
    events:
      - schedule: cron(0 1 ? * MON *)

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true


