app: warmapp
service: warmapp-1
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  profile: warmapp

package:
  exclude:
    - node_modules/**
    - __pycache__/**
    - .serverless/**
    - .venv/**

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements
  - serverless-offline # for local development
