service: lambda-processor

provider:
  name: aws
  runtime: python3.11

functions:
  process:
    handler: handler.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - data-raw-q
              - Arn
