service: lambda-crud
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

functions:
  health:
    handler: handler.health
    events:
      - http:
          path: health
          method: get
