service: lambda-scraper
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  timeout: 100

package:
  exclude:
    - node_modules/**
    - __pycache__/**
    - .serverless/**
    - .venv/**

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements
  - serverless-offline # for local development

custom:
  serverless-offline:
    host: 0.0.0.0
    port: 3000