service: lambda-crud

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  crud:
    handler: handler.health
    events:
      - http:
          path: health
          method: get
