service: processor
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  timeout: 100
  region: us-east-1
  environment:
    QUEUE_URL:
      Ref: firstQueue
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:GetQueueAttributes
      Resource:
        Fn::GetAtt: [data-raw-q, Arn]

package:
  exclude:
    - node_modules/**
    - __pycache__/**
    - .serverless/**
    - .venv/**

functions:
  api:
    handler: handler.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - firstQueue
              - Arn
          enabled: true
resources:
  Resources:
    firstQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: data-raw-q


plugins:
  - serverless-python-requirements
  - serverless-offline # for local development
  - serverless-offline-sqs

custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://sqs:9324
    region: us-east-1
    accessKeyId: local
    secretAccessKey: local
    queues:
      - QueueName: data-raw-q