version: '3'
services:
  backend:
    build:
      context: .
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_DEFAULT_REGION=us-west-1
      - SERVERLESS_ACCESS_KEY=AKLLyRmFbLiHfhN2w3dB9XxP5H3wbShO3pmOLubX0kXSg

