service: lambda-scraper
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

functions:
  scrape:
    handler: handler.scrape
    events:
      - http:
          path: scrape
          method: post