service: lambda-scraper

provider:
  name: aws
  runtime: python3.11
  region: us-east-1  

functions:
  scrape:
    handler: handler.scrape
    events:
      - http:
          path: scrape
          method: post
