service: lambda-processor
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

functions:
  process:
    handler: handler.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - "test-queue"
              - "Arn"
