service: scraper-service

provider:
  name: aws
  runtime: python3.11

functions:
  scrape:
    handler: handler.scrape_data
    events:
      - http:
          path: scrape
          method: post

  health:
    handler: handler.health_check
    events:
      - http:
          path: health
          method: get
